version: "3.8"
services:
  #php
  app:
    container_name: php
    build: ./infra/php
    volumes:
      - ./backend:/work

  #nginx
  web:
    container_name: nginx
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 33060:3306

volumes:
  db-store:
